### ISSUE TITLE
How can i contribute? 

### ISSUE THREAD

**Issue by theonewhoknocks878** [saarock/notty.js#21]
Hi, i contributed once in here  but with the web editor of GitHub, in Visual Studio Code there's errors when i do `git push` and it says that i don't have permissions (probably bc the terminal thinks that i am doing the push on the main branch).

So how can i contribute with Visual studio Code??

**Comment by theonewhoknocks878** [comment]
@angeldevildev @saarock

**Comment by angeldevildev** [comment]
Here people can write issue about the project, so you shouldn't ask here, all the informations about how to contribute are in the `CONTRIBUTING.md` file, after you commited all the files that you changed run the command `git push` and then copy and paste the command that there will be printed in the terminal. Then after the push in your fork you can create a PR (Pull Request) in there.

**Comment by theonewhoknocks878** [comment]
Thanks
