### ISSUE TITLE
Notty Toast animation related 

### ISSUE THREAD

**Issue by saarock** [saarock/notty.js#7]
**Create a beautiful bounce effect while showing and leaving the toast.**

**Comment by Vedant817** [comment]
I would love to contribute for the issue.

**Comment by saarock** [comment]
> I would love to contribute for the issue.

Thank you so much for your interest in contributing! We’re thrilled to have your support. Please feel free to dive into the issue, and let us know if you need any guidance or additional information. Your contributions are greatly appreciated and will make a significant impact!
